//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Voucher_Or_Coupons_Details
    {
        public string id { get; set; }
        public string Bill_Id { get; set; }
        public string Voucher_Coupon_Code { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
    }
}
