//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string id { get; set; }
        public string Bill_Type { get; set; }
        public string Bill_Id { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<System.TimeSpan> Bill_Time { get; set; }
        public Nullable<decimal> Net_Total_Amount { get; set; }
        public string Discount_Type { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Discount_Amount { get; set; }
        public string Tax_Type { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Service_Charges { get; set; }
        public string Voucher_Or_Coupon_Id { get; set; }
        public Nullable<decimal> Vouchar_Coupon_Discount_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string C_Description { get; set; }
        public string Customer_Vendor_Id { get; set; }
        public string Payment_Method { get; set; }
        public string Card_Number { get; set; }
        public string Card_Holder_Name { get; set; }
        public string Card_Transaction_No { get; set; }
        public string Card_Type { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Security_Code { get; set; }
        public string Cheque_No { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Account_No { get; set; }
        public string Payment_Note { get; set; }
        public string AddedBy_UserId { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<System.TimeSpan> C_Time { get; set; }
        public string Status { get; set; }
    }
}
