//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Details
    {
        public string id { get; set; }
        public string Bill_Id { get; set; }
        public string Item_Id { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<System.DateTime> Manufacturing_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Batch_Or_Lot_Number { get; set; }
        public string Status { get; set; }
        public string item_type { get; set; }
        public string update_status { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<decimal> mazdori { get; set; }
    }
}
