//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Or_Vendor
    {
        public string id { get; set; }
        public string Customer_Vendor_Type { get; set; }
        public string customer_Or_Vendor_Name { get; set; }
        public string Contact_Number { get; set; }
        public string C_Address { get; set; }
        public string AddedBy_UserId { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<System.TimeSpan> C_Time { get; set; }
        public string status { get; set; }
        public string parent { get; set; }
        public string Percentage { get; set; }
    }
}
