//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string id { get; set; }
        public string sku { get; set; }
        public string Name { get; set; }
        public string Brand_Id { get; set; }
        public string Unit_Id { get; set; }
        public string Category_Id { get; set; }
        public string Barcode { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<decimal> Purchase_Price { get; set; }
        public Nullable<decimal> Retail_Price { get; set; }
        public string Have_Mfg_Or_Exp_Date { get; set; }
        public string Have_Batch_Or_Lot_No { get; set; }
        public Nullable<decimal> AlertQty { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Detail { get; set; }
        public string AddedBy_UserId { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<System.TimeSpan> C_Time { get; set; }
        public string Status { get; set; }
        public string weight { get; set; }
        public string update_status { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<decimal> Mazdori { get; set; }
    }
}
