//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginlog
    {
        public string Id { get; set; }
        public string Login_Userid { get; set; }
        public Nullable<System.DateTime> Login_Date { get; set; }
        public Nullable<System.TimeSpan> Login_Time { get; set; }
        public string Status { get; set; }
    }
}
