//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POS_Sabzi_MandiEntities : DbContext
    {
        public POS_Sabzi_MandiEntities()
            : base("name=POS_Sabzi_MandiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill> Bills { get; set; }
        public DbSet<Bill_Details> Bill_Details { get; set; }
        public DbSet<Bill_Voucher_Or_Coupons_Details> Bill_Voucher_Or_Coupons_Details { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer_Or_Vendor> Customer_Or_Vendor { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<loginlog> loginlogs { get; set; }
        public DbSet<mml> mmls { get; set; }
        public DbSet<printed_bills_log> printed_bills_log { get; set; }
        public DbSet<setting> settings { get; set; }
        public DbSet<Tax> Taxes { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<Voucher_Or_Coupons> Voucher_Or_Coupons { get; set; }
    }
}
