//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public string id { get; set; }
        public string setting_code { get; set; }
        public string setting1 { get; set; }
        public string value { get; set; }
        public string AddedBy_UserId { get; set; }
        public Nullable<System.DateTime> C_date { get; set; }
        public Nullable<System.TimeSpan> C_time { get; set; }
        public string status { get; set; }
    }
}
