//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher_Or_Coupons
    {
        public string id { get; set; }
        public string Voucher_Coupon_Code { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public string C_Description { get; set; }
        public string Status { get; set; }
    }
}
